# Generated by Django 5.2 on 2025-04-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MWF', 'Monday-Wednesday-Friday'), ('TTH', 'Tuesday-Thursday'), ('TTHS', 'Tuesday-Thursday-Saturday')], max_length=4),
        ),
    ]
